name: Bob the Builder

on:
  push:
    branches:
      - '*'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    container:
      # We use an Alpine Linux container with some preselect tools and
      # tweaks to facilitate building, but also testing SMCRoute.  We
      # cannot run with --cap-add=NET_ADMIN anymore because the tests
      # use `unshare -mrun foo`, which require privileged mode.
      image: ghcr.io/troglobit/misc
      options: --privileged
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Configure & Build
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        run: |
          ./autogen.sh
          ./configure --prefix= --disable-silent-rules --enable-mrdisc CC=${{ matrix.compiler }}
          make -j3
      - name: Install to ~/tmp and Inspect
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/sbin/smcrouted
          size ~/tmp/sbin/smcrouted
          ldd ~/tmp/sbin/smcroutectl
          size ~/tmp/sbin/smcroutectl
          ~/tmp/sbin/smcrouted -h
          ~/tmp/sbin/smcroutectl -h
      - name: Run Unit Tests
        # Each unit test runs in an unshare and need a custom build of
        # nemesis to support IPv6 UDP injection (hence the container).
        # Note: for some reason we need to run with make -j1 ...
        run: |
          make check
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: smcroute-test-${{ matrix.compiler }}
          path: test/*
