name: Bob the Builder

# Run on all branches, including all pull requests, except the 'dev'
# branch since that's where we run Coverity Scan (limited tokens/day)
on:
  push:
    branches:
      - '**'
      - 'dev'
  pull-request:
    branches:
      - '**'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    container:
      # We use an Alpine Linux container with some preselect tools and
      # tweaks to facilitate building, but also testing SMCRoute.  We
      # cannot run with --cap-add=NET_ADMIN anymore because the tests
      # use `unshare -mrun foo`, which require privileged mode.
      image: ghcr.io/troglobit/misc
      options: --privileged
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    env:
      MAKEFLAGS: -j3
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        # Build in a sub-directory so we can safely set a+w on all
        # directories.  Needed for `make check` since it runs with
        # root dropped and wants to write .trs and .log files.
        run: |
          set -x
          OPTS="--cache-file=/tmp/config.cache --prefix= --enable-mrdisc --enable-test"
          ./autogen.sh
          ./configure $OPTS
          make dist && archive=$(ls *.tar.gz)
          if [ -n "$archive" -a -f "$archive" ]; then
            tar xf "$archive"
            dir=$(echo "$archive" |rev |cut -f3- -d. |rev)
            cd "$dir"
          fi
          mkdir -p .build/dir
          cd .build/dir
          ../../configure $OPTS
          chmod -R a+w .
      - name: Build
        run: |
          make
      - name: Install to ~/tmp and Inspect
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/sbin/smcrouted
          size ~/tmp/sbin/smcrouted
          ldd ~/tmp/sbin/smcroutectl
          size ~/tmp/sbin/smcroutectl
          ~/tmp/sbin/smcrouted -h
          ~/tmp/sbin/smcroutectl -h
      - name: Run Unit Tests
        # Each unit test runs in an unshare and need a custom build of
        # nemesis to support IPv6 UDP injection (hence the container).
        run: |
          make check || cat test/test-suite.log
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: smcroute-test-${{ matrix.compiler }}
          path: test/*
