name: Bob the Builder

on:
  push:
    branches: [master]

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    container:
      # We use an Alpine Linux container with some preselect tools and
      # tweaks to facilitate building, but also testing SMCRoute.  Only
      # in docker is it allowed to create network interfaes and set up
      # routing, no IPv6 addresses available yet though.
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Configure & Build
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        run: |
          ./autogen.sh
          ./configure --disable-silent-rules --enable-mrdisc --prefix=
          make -j3
      - name: Install to ~/tmp and Inspect
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/sbin/smcrouted
          size ~/tmp/sbin/smcrouted
          ldd ~/tmp/sbin/smcroutectl
          size ~/tmp/sbin/smcroutectl
          ~/tmp/sbin/smcrouted -h
          ~/tmp/sbin/smcroutectl -h
      - name: Run Unit Tests
        # Need to run tests in serial, they use same interface names and
        # we also cannot be sure if we run on a kernel with support for
        # multicast policy routing, hence only one smcroute at a time
        run: |
          make check
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: smcroute-test-${{ matrix.compiler }}
          path: test/*

