name: Bob the Builder

on:
  push:
    branches: [master]
env:
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
  MAKEFLAGS: -j2

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: Configure & Build
        run: |
          ./autogen.sh
          ./configure --disable-silent-rules --enable-mrdisc --prefix=
          make
      - name: Install
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/sbin/smcrouted
          size ~/tmp/sbin/smcrouted
          ldd ~/tmp/sbin/smcroutectl
          size ~/tmp/sbin/smcroutectl
          ~/tmp/sbin/smcrouted -h
          ~/tmp/sbin/smcroutectl -h
      - name: Test
        run: |
          make check

